version: '3.7'
services:
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        ports:
          - "53:53/tcp"
          - "53:53/udp"
          - "80:80/tcp"
        environment:
          TZ: 'America/New York'
          # WEBPASSWORD: 'set a secure password here or it will be random'
        volumes:
          - './etc-pihole:/etc/pihole'
          - './etc-dnsmasq.d:/etc/dnsmasq.d'
        restart: unless-stopped
        networks:
          homelab:
            ipam:
              driver: macvlan
              config:
                - subnet: "192.168.23.0/24"
            ipv4_address: 192.168.23.1
    portainer-ce:
        ports:
            - 9002:9000
            - 9444:9443
        container_name: portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /srv/dev-disk-by-label-MYSSD/AppData/portainer-bak:/data
        image: portainer/portainer-ce:2.11.0regal 
        networks:
          homelab:
            ipv4_address: 192.168.23.2       
    guacamole:
        restart: always
        container_name: guacamole
        ports:
            - '8080:8080'
        volumes:
            - '$(pwd)/config:/config'
            - '$(pwd)/webapps:/usr/local/tomcat/webapps'
        image: oznu/guacamole
        networks:
          homelab:
            ipv4_address: 192.168.23.3  
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/New York
        volumes:
          - /path/to/library:/config
          - /path/to/tvseries:/data/tvshows
          - /path/to/movies:/data/movies
        ports:
          - 8096:8096
          - 8920:8920 #optional
          - 7359:7359/udp #optional
          - 1900:1900/udp #optional
        restart: unless-stopped
        networks:
          homelab:
            ipv4_address: 192.168.23.4   
    file-browser:
        image: filebrowser/filebrowser
        container_name: file-browser
        user: 1000:1000
        ports:
          - 8081:80
        volumes:
          - /home/serveradmin/:/srv
          - /home/serveradmin/filebrowser/filebrowser.db:/database.db
        restart: unless-stopped
        security_opt:
          - no-new-privileges:true    
        networks:
          homelab:
            ipv4_address: 192.168.23.4 